eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  # client:
    # to prevent server from register itself within Eureka and to allow it
    # only fetch the information about other registered services.
    # registerWithEureka: false

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500

feign:
  hystrix:
    enabled: false

# Регістр в імені сервіса грає роль. Має буть такий самий як використовується при звертанні до сервіса.
time-service:
  ribbon:
    # для Feign ця опція працює. Для RestTemplate
    # треба все це налаштовувати через ClientHttpRequestFactory
    ConnectTimeout: 500
    MaxAutoRetriesNextServer: 2

DATE-SERVICE:
  ribbon:
    MaxAutoRetriesNextServer: 2


#### Loggers ####
logging.level:
  my.example.datetime.TimeFeignClient: DEBUG
  # org.springframework: DEBUG