spring:
  http:
    converters:
      preferred-json-mapper: "gson"

#eureka:
#  client:
#    healthcheck:
#      enabled: true
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}